### PR TITLE
Added functionality

### PR DESCRIPTION
**Pull request by ir4klis**
16-May-2018
--------------------
Fixes and improvements

### CODE REVIEW

**Comment by ir4klis** [comment]
16-May-2018-v2
-----------------------
### Added assembly version for x86-64 machines.

**Comment by ir4klis** [comment]
### Added some more improvements.

**Comment by ir4klis** [comment]
But it is only one folder. I renamed it in the later version.

**Comment by Parou** [comment]
Well... The repo doesn't think so (and yours neither). And the best part is, I can't even do anything about it because currently the whole repo is fucked up for me. I can literally do nothing.

**Comment by ir4klis** [comment]
Damn. The "assembly" folder shouldn't be there. Just noticed it.

**Pull request merged**
